spring:
  config:
    import: optional:classpath:application-secret.properties
  datasource:
    url: jdbc:postgresql://database-1.ch0222kkis68.ap-northeast-2.rds.amazonaws.com/capstone
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # create / update / none 중 선택
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    disable-swagger-default-url: true
    urls:
      - url: https://13-209-30-220.nip.io/v3/api-docs

